apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc1
spec:
  replicas: 1
  selector:
   dc: IN
  template:
    metadata:
      name: "mypod"
      labels:
        dc: IN
    spec:
      containers:
      - name: "myc1"
        image: "vimal13/apache-webserver-php"


    
